# Generated by Django 5.0.4 on 2024-09-04 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reserva", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="productos",
        ),
    ]
