# Generated by Django 5.0.4 on 2024-08-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producto", "0002_rename_precio_producto_precio_base_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variante",
            name="imagenes",
            field=models.ManyToManyField(blank=True, to="producto.imagen"),
        ),
    ]
