# Generated by Django 5.0.4 on 2024-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producto", "0003_variante_imagenes"),
    ]

    operations = [
        migrations.AddField(
            model_name="variante",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
