# Generated by Django 5.0.4 on 2024-08-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producto", "0004_variante_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="variante",
            name="imagen",
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagenes",
            field=models.ManyToManyField(
                blank=True, related_name="productos", to="producto.imagen"
            ),
        ),
        migrations.AlterField(
            model_name="variante",
            name="imagenes",
            field=models.ManyToManyField(
                blank=True, related_name="variantes", to="producto.imagen"
            ),
        ),
    ]
