# Generated by Django 5.0.4 on 2024-09-01 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producto", "0005_remove_producto_imagen_remove_variante_imagen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="contacto_de_referencia",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="stock_disponible",
        ),
        migrations.CreateModel(
            name="Subproducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "imagenes",
                    models.ManyToManyField(
                        blank=True, related_name="subproductos", to="producto.imagen"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subproductos",
                        to="producto.producto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Variante",
        ),
    ]
