# Generated by Django 5.0.4 on 2024-09-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producto", "0008_producto_creado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="es_visible",
            field=models.BooleanField(default=True),
        ),
    ]
