# Generated by Django 5.0.4 on 2024-09-04 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productos", models.TextField()),
                ("cantidad_total", models.PositiveIntegerField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.CharField(max_length=10)),
                ("fecha_reserva", models.DateTimeField()),
                (
                    "fecha_historial",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
